version: "3.8"

services:
  # Reverse Proxy - Nginx
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/ssl/certs
    depends_on:
      - web
      - api
    restart: always
    networks:
      - cosmo-network

  # Frontend
  web:
    container_name: ${COMPOSE_PROJECT_NAME}-web
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
      args:
        - NODE_ENV=production
    environment:
      # Next.js
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_INTERNAL_URL=http://api:4000

      # QuickBooks
      - QUICKBOOKS_CLIENT_ID=${QUICKBOOKS_CLIENT_ID}
      - QUICKBOOKS_CLIENT_SECRET=${QUICKBOOKS_CLIENT_SECRET}
      - QUICKBOOKS_REDIRECT_URI=${QUICKBOOKS_REDIRECT_URI}
      - QUICKBOOKS_ENVIRONMENT=${QUICKBOOKS_ENVIRONMENT}
    depends_on:
      - api
    restart: always
    networks:
      - cosmo-network
    expose:
      - "3000"

  # Backend API
  api:
    container_name: ${COMPOSE_PROJECT_NAME}-api
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
      args:
        - NODE_ENV=production
    environment:
      # Database
      - DATABASE_URL=${DATABASE_URL}

      # Redis
      - REDIS_URL=${REDIS_URL}

      # JWT & Auth
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - FRONTEND_URL=${FRONTEND_URL}

      # AI
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
      - DEFAULT_AI_PROVIDER=${DEFAULT_AI_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Rate Limiting
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - cosmo-network
    expose:
      - "4000"

  # Base de datos PostgreSQL
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-backup:/backup
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - cosmo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - "5432"

  # Redis Cache
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - cosmo-network
    healthcheck:
      test: ["CMD", "redis-cli", "auth", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    expose:
      - "6379"

volumes:
  postgres-data:
  redis-data:

networks:
  cosmo-network:
    driver: bridge
