# Este archivo se carga automáticamente en desarrollo
version: "3.8"

services:
  api:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/api/dist
    command: yarn workspace @cosmo/api dev

  web:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    command: yarn workspace @cosmo/web dev
