version: "3.8"

services:
  # Reverse Proxy - Nginx
  nginx:
    container_name: cosmo-nginx-prod
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/ssl/certs
    depends_on:
      - web
      - api
    restart: always
    networks:
      - cosmo-network

  # Frontend
  web:
    container_name: cosmo-web-prod
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://${DOMAIN}/api
      - NEXTAUTH_URL=https://${DOMAIN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - api
    restart: always
    networks:
      - cosmo-network
    expose:
      - "3000"

  # Backend API
  api:
    container_name: cosmo-api-prod
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - PORT=4000
      - FRONTEND_URL=https://${DOMAIN}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
      - DEFAULT_AI_PROVIDER=${DEFAULT_AI_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - cosmo-network
    expose:
      - "4000"

  # Base de datos PostgreSQL
  postgres:
    container_name: cosmo-postgres-prod
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-backup:/backup
    restart: always
    networks:
      - cosmo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - "5432"

  # Redis Cache
  redis:
    container_name: cosmo-redis-prod
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - cosmo-network
    expose:
      - "6379"

networks:
  cosmo-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
