name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-staging:
    name: Deploy to Staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      
      # Aquí se agregarían los pasos específicos para desplegar en staging
      # Por ejemplo, usando AWS CLI, Heroku, o Docker
      
      # Ejemplo para instalar AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      # Por ahora solo mostramos un mensaje
      - name: Deploy staging (placeholder)
        run: echo "Deployment to staging would happen here"
        
  notify:
    name: Notify team
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      # Envío de notificación (por ejemplo, a Slack)
      - name: Notify team (placeholder)
        run: echo "Notification would be sent here" 